#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "dark_plus"

    colorscheme = "vividchalk"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

    disabled_plugins = ["neomake"]

    relativenumber = true

    # Bootstrap
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
 

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

# Shell Layer
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

#Colorscheme layer
[[layers]]
  name = "colorscheme"

#Statusline layer
[[layers]]
  name = "core#statusline"

# CUSTOM PLUGINS

[[custom_plugins]]
  repo = "severin-lemaignan/vim-minimap"
  merged = true

[[custom_plugins]]
  repo = "mg979/vim-studio-dark"
  merged = true

[[custom_plugins]]
  repo = "rdnetto/YCM-Generator"
  merged = true

[[custom_plugins]]
  repo = "jiangmiao/auto-pairs"
  merged = true

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = true

[[custom_plugins]]
  repo = "sheerun/vim-polyglot"
  merged = true

[[custom_plugins]]
  repo = "https://github.com/mg979/vim-visual-multi"
  merged = true
 
[[custom_plugins]]
  repo = "https://github.com/tpope/vim-commentary"
  merged = true

[[custom_plugins]]
  repo = "SirVer/ultisnips"
  merged = true

[[custom_plugins]]
  repo = "prabirshrestha/asyncomplete.vim"
  merged = true

[[custom_plugins]]
  repo = "andreypopp/asyncomplete-ale.vim"
  merged = false

[[custom_plugins]]
  repo = "dominikduda/vim_current_word"
  merged = false

[[custom_plugins]]
  repo = "ycm-core/YouCompleteMe"
  merged = false

[[custom_plugins]]
  repo = "tpope/vim-fugitive"
  merged = false

[[custom_plugins]]
  repo = "vim-syntastic/syntastic"
  merged = false

[[custom_plugins]]
  repo = "ilyachur/cmake4vim"
  merged = false

[[custom_plugins]]
  repo = "Yggdroot/indentLine"
  merged = false

[[custom_plugins]]
  repo = "OmniSharp/omnisharp-vim"
  merged = false

[[custom_plugins]]
  repo = "nickspoons/vim-sharpenup"
  merged = false

[[custom_plugins]]
  repo = "neoclide/coc.nvim"
  merged = false

[[custom_plugins]]
  repo = "google/vim-colorscheme-primary"
  merged = false

[[custom_plugins]]
  repo = "broduo/broduo-color-scheme"
  merged = false

[[custom_plugins]]
  repo = "sblauen/chalk"
  merged = false

[[custom_plugins]]
  repo = "justb3a/vim-smarties"
  merged = false

[[custom_plugins]]
  repo = "ghifarit53/tokyonight-vim"
  merged = false

[[custom_plugins]]
  repo = "nonetallt/vim-neon-dark"
  merged = false

[[custom_plugins]]
  repo = "dunstontc/vim-vscode-theme"
  merged = false

[[custom_plugins]]
  repo = "tomsik68/vim-crystallite"
  merged = false

[[custom_plugins]]
  repo = "tpope/vim-vividchalk"
  merged = false

[[custom_plugins]]
  repo = "skammer/vim-css-color"
  merged = true

# --------------------------------------------------
